"""Enforce that the viewer's "What's new" feed stays in step with the sources.

`family-tree-viewer/updates.json` is generated by `scripts/build_updates.py` and
must be regenerated (`make updates`) whenever a source is catalogued. Nothing used
to fail when it drifted, so a catalogued source could silently never appear in the
feed. Every non-private source becomes a feed entry (either its own auto entry, or
— when a curated `updates.yaml` entry references it — via that curated entry), so
this test asserts every public source id is present somewhere in the feed.
"""

from __future__ import annotations

import glob
import json
import unittest
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
UPDATES_PATH = PROJECT_ROOT / "family-tree-viewer" / "updates.json"
SOURCES_GLOB = str(PROJECT_ROOT / "data" / "sources" / "*" / "*.yaml")


class UpdatesFeedTests(unittest.TestCase):
    def test_every_public_source_appears_in_updates_feed(self) -> None:
        payload = json.loads(UPDATES_PATH.read_text(encoding="utf-8"))
        present: set[str] = set()
        for entry in payload.get("updates", []):
            primary = entry.get("primary")
            if isinstance(primary, str):
                present.add(primary)
            for link in entry.get("links") or []:
                if isinstance(link, str):
                    present.add(link)

        missing: list[str] = []
        for path in sorted(glob.glob(SOURCES_GLOB)):
            with open(path, encoding="utf-8") as handle:
                source = yaml.safe_load(handle) or {}
            sid = source.get("id")
            if not isinstance(sid, str) or source.get("private"):
                continue  # private (living-adjacent) records never surface in the feed
            if sid not in present:
                missing.append(sid)

        self.assertEqual(
            [],
            missing,
            "family-tree-viewer/updates.json is stale — these public sources are "
            "absent from the feed; regenerate it with `make updates`: "
            + ", ".join(missing),
        )


if __name__ == "__main__":
    unittest.main()
